variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths:
  - .stack/
  - .stack-work/
  - .cabal-sandbox/

stages:
  - build

.job_template: &common_script
  script:
    - stack upgrade
    - stack $RESOLVER build $GHCVERSION
    - stack $RESOLVER test $GHCVERSION

.job_template_cabal: &cabal_script
  script:
    - cabal update
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests
    - cabal build
    - cabal test

job-saved-lts:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-lts.yaml
    GHCVERSION: --system-ghc
  <<: *common_script

job-current-lts:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-lts.yaml
    RESOLVER: --resolver lts
    GHCVERSION: --system-ghc
  <<: *common_script

job-saved-nightly:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack.yaml
    GHCVERSION: --system-ghc
  <<: *common_script

# job-current-nightly:
#   image: haskell:8.2.1
#   stage: build
#   variables:
#     STACK_YAML: stack.yaml
#     RESOLVER: --resolver nightly
#     GHCVERSION: --system-ghc
#   <<: *common_script

job-hackage-ghc802:
  image: haskell:8.0.2
  stage: build
  <<: *cabal_script
