variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack

cache:
  paths:
  - .stack/
  - .stack-work/
  - .cabal-sandbox/

stages:
  - build

.job_template: &common_script
  script:
    - stack build --system-ghc
    - stack test --system-ghc

.job_template_cabal: &cabal_script
  script:
    - cabal update
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests
    - cabal build
    - cabal test

job-ghc801-pandoc117:
  image: haskell:8.0.1
  stage: build
  variables:
    STACK_YAML: stack-ghc8-pandoc117.yaml
  <<: *common_script

job-ghc710-pandoc117:
  image: haskell:7.10.3
  stage: build
  variables:
    STACK_YAML: stack-ghc7-pandoc117.yaml
  <<: *common_script

job-ghc801-pandoc118:
  image: haskell:8.0.1
  stage: build
  variables:
    STACK_YAML: stack-ghc8-pandoc118.yaml
  <<: *common_script

job-ghc710-pandoc118:
  image: haskell:7.10.3
  stage: build
  variables:
    STACK_YAML: stack-ghc7-pandoc118.yaml
  <<: *common_script

job-ghc801-pandoc119:
  image: haskell:8.0.1
  stage: build
  variables:
    STACK_YAML: stack-ghc8-pandoc119.yaml
  <<: *common_script

job-ghc710-pandoc119:
  image: haskell:7.10.3
  stage: build
  variables:
    STACK_YAML: stack-ghc7-pandoc119.yaml
  <<: *common_script

job-hackage-ghc710:
  image: haskell:7.10.3
  stage: build
  <<: *cabal_script

job-hackage-ghc801:
  image: haskell:8.0.1
  stage: build
  <<: *cabal_script
