variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack

cache:
  paths:
  - .stack/
  - .stack-work/

stages:
  - build

.job_template: &common_script
  script:
    - stack build
    - stack test

job-ghc802-pandoc117:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-ghc8-pandoc117.yaml
  <<: *common_script

job-ghc802-pandoc118:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-ghc8-pandoc118.yaml
  <<: *common_script

job-ghc710-pandoc117:
  image: haskell:7.10.3
  stage: build
  variables:
    STACK_YAML: stack-ghc7-pandoc117.yaml
  <<: *common_script

job-ghc710-pandoc118:
  image: haskell:7.10.3
  stage: build
  variables:
    STACK_YAML: stack-ghc7-pandoc118.yaml
  <<: *common_script
