variables:
  STACK_ROOT: $CI_PROJECT_DIR/.stack

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths:
  - .stack/
  - .stack-work/
  - .cabal-sandbox/

stages:
  - build

.job_template: &common_script
  script:
    - stack $RESOLVER build --system-ghc
    - stack $RESOLVER test --system-ghc

.job_template_cabal: &cabal_script
  script:
    - cabal update
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests
    - cabal build
    - cabal test

job-saved-lts:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-lts.yaml
  <<: *common_script

job-current-lts:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack-lts.yaml
    RESOLVER: --resolver lts
  <<: *common_script

job-saved-nightly:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack.yaml
  <<: *common_script

job-current-nightly:
  image: haskell:8.0.2
  stage: build
  variables:
    STACK_YAML: stack.yaml
    RESOLVER: --resolver nightly
  <<: *common_script

job-hackage-ghc802:
  image: haskell:8.0.2
  stage: build
  <<: *cabal_script
