language: c
sudo: true

cache:
  directories:
   - $HOME/.cabal/
   - $HOME/.ghc/

addons:
  homebrew:
    packages:
    - ghc
    - cabal-install
    - upx

env:
  global:
    - secure: "JlX01XMktACOHe7p+aQr60dwTVRu1GHzbx6dFAQpg+LtFq3GuSsJbpprRRjVaXHQzQh4TQLaNuktOuB9u042+SDZl52xwIpn8ViTiNnH1QMCMzzPMrOMhNkE+3Z4BIWWe4PBKdPHdBxwanhOMh1BIxWrq3wy//PEOG9qJqJgLWw="
    - RUN_UPX: yes
    - DOCKER_IMAGE_VERSION: latest

services:
  - docker

os:
  - linux
  - osx

script:
- export -f travis_retry
# Output something every 9 minutes (540 seconds) or Travis kills the job
- while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
- "${TRAVIS_OS_NAME}/build.sh"
# Kill the sleep loop
- kill %1
# Print built version string
- ./pandoc-crossref -v
- RELEASE_FN=( *-pandoc_*.tar.gz )
- travis_retry curl -T "$TRAVIS_BUILD_DIR/$RELEASE_FN" -ulierdakil:$BINTRAY_API_KEY "https://api.bintray.com/content/lierdakil/pandoc-crossref/pandoc-crossref/nightly/build-$(date -u +%FT%T)-$TRAVIS_BRANCH-$(git rev-parse --short HEAD)-$RELEASE_FN?publish=1"
deploy:
  provider: releases
  api_key:
    secure: HgG0wburBoUnULjqK3I86k9ZNVLks4/WXPicd7rn2z8HbFpFv/QVN6882hYbsWQd3xhe+Q+hTfXMSL2lbZpiEKAB3UgQclJMP84A42DyvS6RE5a+kwl/wVVNXQh4sNlzuApTSzjYZZkYvroyakqsucCRg7u56eN4NM2VvrDUuJw=
  file: $TRAVIS_BUILD_DIR/*-pandoc_*.tar.gz
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
