language: c
sudo: true

cache: false

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
  - env: STACK_YAML=stack-release.yaml RELEASE_FN=ghc86-pandoc24
    compiler: ": #GHC 8.6"
  - env: STACK_YAML=stack-release.yaml RELEASE_FN=ghc86-pandoc24
    compiler: ": #GHC 8.6"
    os: osx

before_install:
- unset CC
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then STACK_OS=osx-x86_64 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then STACK_OS=linux-x86_64 ; fi
- travis_retry curl -L https://www.stackage.org/stack/$STACK_OS | tar xz --strip-components=1 -C ~/.local/bin
- travis_wait 30 stack --no-terminal setup
script:
- travis_wait 90 stack --no-terminal build
deploy:
  provider: releases
  api_key:
    secure: HgG0wburBoUnULjqK3I86k9ZNVLks4/WXPicd7rn2z8HbFpFv/QVN6882hYbsWQd3xhe+Q+hTfXMSL2lbZpiEKAB3UgQclJMP84A42DyvS6RE5a+kwl/wVVNXQh4sNlzuApTSzjYZZkYvroyakqsucCRg7u56eN4NM2VvrDUuJw=
  file: "$TRAVIS_BUILD_DIR/${TRAVIS_OS_NAME}-${RELEASE_FN}.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
before_deploy:
- stack --no-terminal install
- stack --no-terminal exec -- pandoc -s -t man docs/index.md -o $HOME/.local/bin/pandoc-crossref.1
- tar czf "$TRAVIS_BUILD_DIR/${TRAVIS_OS_NAME}-${RELEASE_FN}.tar.gz" -C "$HOME/.local/bin/" "./pandoc-crossref" "./pandoc-crossref.1"
