language: c
sudo: true

cache: false

addons:
  apt:
    packages:
    - libgmp-dev

env:
  - secure: "JlX01XMktACOHe7p+aQr60dwTVRu1GHzbx6dFAQpg+LtFq3GuSsJbpprRRjVaXHQzQh4TQLaNuktOuB9u042+SDZl52xwIpn8ViTiNnH1QMCMzzPMrOMhNkE+3Z4BIWWe4PBKdPHdBxwanhOMh1BIxWrq3wy//PEOG9qJqJgLWw="

services:
  - docker

os:
  - linux
  - osx

script:
- export -f travis_retry
- travis_wait 90 "${TRAVIS_OS_NAME}/build.sh"
- RELEASE_FN=( *-pandoc_*.tar.gz )
- travis_retry curl -T "$TRAVIS_BUILD_DIR/$RELEASE_FN" -ulierdakil:$BINTRAY_API_KEY "https://api.bintray.com/content/lierdakil/pandoc-crossref/pandoc-crossref/nightly/build-$(date -u +%FT%T)-$(git rev-parse HEAD)-$RELEASE_FN?publish=1"
deploy:
  provider: releases
  api_key:
    secure: HgG0wburBoUnULjqK3I86k9ZNVLks4/WXPicd7rn2z8HbFpFv/QVN6882hYbsWQd3xhe+Q+hTfXMSL2lbZpiEKAB3UgQclJMP84A42DyvS6RE5a+kwl/wVVNXQh4sNlzuApTSzjYZZkYvroyakqsucCRg7u56eN4NM2VvrDUuJw=
  file: $TRAVIS_BUILD_DIR/*-pandoc_*.tar.gz
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
