name: pandoc-crossref
version: '0.2.6.0'
synopsis: Pandoc filter for cross-references
description: pandoc-crossref is a pandoc filter for numbering figures, equations,
  tables and cross-references to them.
category: Text
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: GPL-2
license-file: LICENSE.md
github: lierdakil/pandoc-crossref
extra-source-files:
- test/*.inc
- test/m2m/equations/*.md
- test/m2m/equations-auto/*.md
- test/m2m/equations-tables/*.md
- test/m2m/equations-tables-auto/*.md
- test/m2m/subfigures/*.md
- test/m2m/subfigures-grid/*.md
- test/m2m/subfigures-ccsDelim/*.md
- test/m2m/equations/*.tex
- test/m2m/equations-auto/*.tex
- test/m2m/equations-tables/*.tex
- test/m2m/equations-tables-auto/*.tex
- test/m2m/subfigures/*.tex
- test/m2m/subfigures-grid/*.tex
- test/m2m/subfigures-ccsDelim/*.tex
dependencies:
- base >=4.9 && <5
- pandoc ==2.0.*
- pandoc-types ==1.17.*
- mtl >=1.1 && <2.3
- containers >=0.1 && <0.6
- data-default >=0.4 && <0.8
- data-accessor >=0.2.2.6 && <0.3.0.0
- data-accessor-template >=0.2.1.12 && <0.3.0.0
- data-accessor-transformers >=0.2.1.6 && <0.3.0.0
- template-haskell >=2.7.0.0 && <3.0.0.0
- roman-numerals ==0.5.*
- syb >=0.4 && <0.8
- utility-ht >=0.0.11 && <0.1.0
- directory >=1 && <1.4
- filepath >=1.1 && <1.5
- text >=1.2.2 && <1.3
library:
  source-dirs: lib
  ghc-options: -Wall
  exposed-modules:
  - Text.Pandoc.CrossRef
executables:
  pandoc-crossref:
    main: pandoc-crossref.hs
    source-dirs: src
    ghc-options: -Wall
    dependencies:
    - pandoc-crossref
tests:
  test-pandoc-crossref:
    main: test-pandoc-crossref.hs
    source-dirs:
    - test
    - lib
    ghc-options:
    - -rtsopts
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
      - hspec
  test-integrative:
    main: test-integrative.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - hspec
data-files:
- demo.md
