flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  pandoc: -j "+RTS -A64m -RTS"
  pandoc-citeproc: -j "+RTS -A64m -RTS"
  $targets: -j "+RTS -A64m -RTS"
packages:
- .
extra-deps:
- roman-numerals-0.5.1.5
- data-accessor-template-0.2.1.16
- pandoc-2.11
- pandoc-types-1.22
# pandoc dependencies
- citeproc-0.1
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.1
- hslua-1.2.0
- jira-wiki-markup-1.3.2
- skylighting-0.10.0.2
- skylighting-core-0.10.0.2
resolver: lts-16.18
