flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  pandoc: -j "+RTS -A64m -RTS"
  pandoc-citeproc: -j "+RTS -A64m -RTS"
  $targets: -j "+RTS -A64m -RTS"
packages:
- .
extra-deps:
- roman-numerals-0.5.1.5
- data-accessor-template-0.2.1.16
- pandoc-2.10.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- pandoc-types-1.21
- commonmark-0.1.0.1
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.0
resolver: lts-16.7
