flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  $targets: -optl-fuse-ld=bfd -j "+RTS -A64m -RTS"
  pandoc: -j "+RTS -A64m -RTS"
  pandoc-citeproc: -j "+RTS -A64m -RTS"
packages: [.]
extra-deps:
- roman-numerals-0.5.1.5
resolver: lts-15.2
