flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  pandoc: -j "+RTS -A64m -RTS"
  pandoc-citeproc: -j "+RTS -A64m -RTS"
  $targets: -j "+RTS -A64m -RTS"
packages:
- .
extra-deps:
- roman-numerals-0.5.1.5
- data-accessor-template-0.2.1.16
resolver: lts-16.3
