flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  $targets: -optl-fuse-ld=bfd
packages:
- .
allow-newer: true # data-accessor-template overrestricts template-haskell dependency
extra-deps:
- roman-numerals-0.5.1.5
- data-accessor-template-0.2.1.16
resolver: nightly-2020-02-04
