flags:
  pandoc-crossref:
    enable_flaky_tests: true
ghc-options:
  pandoc: -j "+RTS -A64m -RTS"
  $targets: -j "+RTS -A64m -RTS"
packages:
- .
extra-deps:
- roman-numerals-0.5.1.5
- pandoc-2.15
- citeproc-0.6
- commonmark-0.2.1.1
- hslua-2.0.0
- hslua-marshalling-2.0.0
- hslua-module-path-1.0.0
- hslua-module-system-1.0.0
- hslua-module-text-1.0.0
- hslua-module-version-1.0.0
- skylighting-0.12.1
- skylighting-core-0.12.1
- texmath-0.12.3.2
- doctemplates-0.10.0.1
- hslua-classes-2.0.0
- hslua-core-2.0.0.1
- hslua-objectorientation-2.0.0
- hslua-packaging-2.0.0
- lua-2.0.0.1
resolver: lts-18.14
