flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- roman-numerals-0.5.1.5
- pandoc-2.0
- cmark-gfm-0.1.3
- doctemplates-0.2.1
- hslua-0.9.2
- pandoc-types-1.17.2
- skylighting-0.4.2
resolver: lts-9.11
