name: Haskell CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pandocver: ["2.10.1"]
        include:
        - os: ubuntu-latest
          container: 'lierdakil/alpine-haskell:8.10.1-pwsh'
          ghcver: '8.10.1'
        - os: macos-latest
          ghcver: '8.10.1'
        - os: windows-latest
          ghcver: '8.8.4'
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      if: '!(matrix.container)'
      with:
        ghc-version: ${{matrix.ghcver}}
        cabal-version: '3.2'
    - name: Cabal init
      shell: pwsh
      run: |
        $store = Join-Path $pwd ".cabal-store"
        New-Item -ItemType Directory -Force "$store"
        cabal user-config init --force --augment="store-dir: $store" `
          --augment="install-method: copy"
    - name: Cabal update
      run: cabal v2-update
    - name: Copy build config
      shell: bash
      run: cp misc/${{runner.os}}-build-cabal-config ./cabal.project
    - name: Cabal confugure
      run: cabal v2-configure --constraint pandoc==${{matrix.pandocver}} --enable-tests
    - uses: actions/cache@v2
      with:
        path: .cabal-store
        key: ${{runner.os}}-${{matrix.ghcver}}-${{matrix.pandocver}}-${{hashFiles('pandoc-crossref.cabal')}}-${{hashFiles('dist-newstyle/cache/plan.json')}}-r1
        restore-keys: |
          ${{runner.os}}-${{matrix.ghcver}}-${{matrix.pandocver}}-${{hashFiles('pandoc-crossref.cabal')}}-${{hashFiles('dist-newstyle/cache/plan.json')}}
          ${{runner.os}}-${{matrix.ghcver}}-${{matrix.pandocver}}-${{hashFiles('pandoc-crossref.cabal')}}
          ${{runner.os}}-${{matrix.ghcver}}-${{matrix.pandocver}}
    - shell: bash
      run: |
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pandoc-crossref-*
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pandoc-crossr_-*
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pndc-crssrf-*
    - name: Install dependencies
      run: cabal v2-build --only-dependencies
    - name: Build
      run: cabal v2-build
    - name: Run tests
      run: cabal v2-test
    - name: Install
      shell: bash
      run: |
        mkdir pandoc-crossref-${{runner.os}}
        export GIT_DIR="$PWD/.git"
        cabal v2-install --installdir=$PWD/pandoc-crossref-${{runner.os}}
    - name: Make manpage
      if: runner.os == 'Linux'
      run: |
        cabal v2-install --installdir="$HOME" pandoc
        "$HOME/pandoc" -s -t man docs/index.md -o pandoc-crossref-${{runner.os}}/pandoc-crossref.1
    - name: Get Version
      shell: bash
      id: get_version
      run: |
        cd pandoc-crossref-${{runner.os}}/
        case "${{runner.os}}" in
        Windows)
            VERSION="$(./pandoc-crossref.exe --version)"
            ;;
        *)  chmod +x pandoc-crossref
            VERSION="$(./pandoc-crossref --version)"
            ;;
        esac
        echo "$VERSION"
        echo "$VERSION" > version.txt
    - uses: actions/upload-artifact@v2
      with:
        name: ${{runner.os}}-build
        path: pandoc-crossref-${{runner.os}}
    - shell: bash
      run: |
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pandoc-crossref-*
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pandoc-crossr_-*
        rm -rvf .cabal-store/ghc-${{matrix.ghcver}}/pndc-crssrf-*

  release:
    needs: [build]
    runs-on: ubuntu-latest
    container: alpine:3.12
    strategy:
      matrix:
        pandocver: ["2.10.1"]
    steps:
    - run: apk add --update --no-cache p7zip upx bash tar xz
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: Repack assets
      run: |
        mkdir assets
        chmod +x Linux-build/pandoc-crossref
        upx Linux-build/pandoc-crossref
        chmod +x macOS-build/pandoc-crossref
        upx macOS-build/pandoc-crossref
        tar cJf assets/pandoc-crossref-Linux-${{github.sha}}.tar.xz -C Linux-build pandoc-crossref pandoc-crossref.1
        tar cJf assets/pandoc-crossref-macOS-${{github.sha}}.tar.xz -C macOS-build pandoc-crossref
        cd Windows-build
        upx pandoc-crossref.exe
        7z a ../assets/pandoc-crossref-Windows-${{github.sha}}.7z pandoc-crossref.exe
    - uses: actions/upload-artifact@v2
      with:
        name: release-assets
        path: assets
    - name: Generate description
      shell: bash
      run: |
        echo -n "" > description.md
        for i in *-build; do
          os="${i%-build}"
          desc="$(cat $i/version.txt)"
          echo "${os}: ${desc}" >> description.md
          echo ::set-output name=${os}::${desc}
        done
        echo "description.md"
        cat description.md
      id: description
    - name: Create release
      if: contains(github.ref, 'tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        assets=()
        for asset in assets/*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        echo -en "$tag_name\n\n" > release.md
        cat description.md >> release.md
        echo "release.md"
        cat release.md
        hub release create "${assets[@]}" -F "release.md" "$tag_name"
        rm release.md
        rm description.md
    - name: Extract branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: extract_branch
    - name: Upload to Bintray
      if: "!contains(github.ref, 'tags/v')"
      uses: lierdakil/action-bintray-upload@master
      with:
        username: lierdakil
        apiKey: ${{secrets.BINTRAY_API_KEY}}
        subject: lierdakil
        repository: pandoc-crossref
        package: ${{steps.extract_branch.outputs.branch}}
        version: ${{github.sha}}
        filesGlob: ./assets/*
        createPkg: true
        versionDescription: |
          Linux: ${{steps.description.outputs.Linux}}
          macOS: ${{steps.description.outputs.macOS}}
          Windows: ${{steps.description.outputs.Windows}}
        licenses: 'GPL-2.0,GPL-3.0-or-later'

  build-stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pandocver: ["2.10.1"]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        wget https://get.haskellstack.org/stable/linux-x86_64-static.tar.gz
        tar zxf linux-x86_64-static.tar.gz
        mv stack-*/stack ./
        chmod +x ./stack
    - uses: actions/cache@v1
      with:
        path: /home/runner/.stack
        key: ${{ runner.os }}-stack
    - name: Build and test
      run: ./stack build --test
    - name: Verify version
      shell: bash
      run: |
        stack exec -- pandoc-crossref --version | grep -q 'Pandoc v${{matrix.pandocver}}'
