name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: lierdakil/pandoc-crossref-build:latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy build config from image
      run: |
        cp -r /root/.cabal "$HOME"
        cp /root/cabal.project.local ./
    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build --only-dependencies --enable-tests
    - name: Build
      run: cabal v2-build
    - name: Run tests
      run: cabal v2-test
    - name: Build artifact
      run:  cabal v2-install --installdir=. --install-method=copy --overwrite-policy=always
    - uses: actions/upload-artifact@v1
      with:
        name: pandoc-crossref
        path: ./pandoc-crossref
